"""
Phase 7 — ON-DEMAND reply-on-my-behalf.

JARVIS NEVER replies to anyone on his own. This runs ONLY when the boss explicitly asks —
"JARVIS, reply to my WhatsApp messages", "answer my Instagram DMs and tell them I'll get back
tomorrow". He triggers it; JARVIS then reads the unread messages on that channel, drafts a
reply to each conversation, sends them, and reports back what he sent.

Two hard rules carried over:
  1. Every reply IDENTIFIES as JARVIS — Aditya's AI assistant — never impersonates Aditya.
  2. It only touches inbound, unmuted, unread conversations, one reply per conversation.

Reply text is generated by the free key-rotated LLM. WhatsApp + Instagram only (email replies
stay manual via reply_email, so nothing is mass-sent from your inbox by accident).
"""

from __future__ import annotations

import asyncio
import logging

from config import CH_WHATSAPP, CH_INSTAGRAM, JARVIS_USER_NAME

logger = logging.getLogger("jarvis.messaging.autoreply")

_SYSTEM = (
    "You are JARVIS, {user}'s personal AI assistant. {user} has asked you to reply to an "
    "incoming {channel} message ON HIS BEHALF. CRITICAL: identify yourself as JARVIS, {user}'s "
    "AI assistant — never pretend to be {user} himself. Be warm and genuinely human — match the "
    "tone of their message (friendly if friendly, gentle if they're upset), brief (one or two "
    "sentences), and personable, never stiff or robotic. Answer the message appropriately. If "
    "they need {user} personally, say you'll pass it on and he'll get back to them. Never invent "
    "facts or commitments. No markdown, no emojis."
)


def _identifies_as_jarvis(text: str) -> bool:
    return "jarvis" in (text or "").lower()


async def draft_reply(channel: str, sender_name: str, body: str, instruction: str = "") -> str | None:
    """Generate one JARVIS-identified reply to a message. Returns None on failure."""
    sys_prompt = _SYSTEM.format(user=JARVIS_USER_NAME, channel=channel)
    user_prompt = f"Message from {sender_name}: {body[:600]}"
    if instruction:
        user_prompt += f"\n\n{JARVIS_USER_NAME}'s instruction for these replies: {instruction}"
    try:
        from app.services.llm.key_rotator import get_rotator
        reply = (await get_rotator().chat(
            [{"role": "system", "content": sys_prompt},
             {"role": "user", "content": user_prompt}], task="chat", temperature=0.5)).strip()
    except Exception as e:  # noqa: BLE001
        logger.warning("reply draft failed (%s)", e)
        return None
    if not reply:
        return None
    if not _identifies_as_jarvis(reply):          # guarantee the identification
        reply = f"(This is JARVIS, {JARVIS_USER_NAME}'s assistant.) " + reply
    return reply


async def reply_to_unread(channel: str, instruction: str = "", contact_filter: str = "",
                          limit: int = 15) -> dict:
    """Reply to unread, unmuted inbound conversations on a channel — one reply per chat.
    Returns {sent: [names], failed: [names], count: n}."""
    if channel not in (CH_WHATSAPP, CH_INSTAGRAM):
        return {"sent": [], "failed": [], "count": 0,
                "error": "I can only auto-reply on WhatsApp or Instagram."}
    from .store import get_store
    store = get_store()

    # Newest unread inbound per conversation (skip muted), most recent first.
    msgs = store.recent(channel=channel, only_unread=True, direction="in",
                        exclude_muted=True, limit=limit * 4)
    cf = contact_filter.lower().strip()
    seen_chats: set[str] = set()
    targets = []
    for m in msgs:
        key = (m.chat_id or m.sender or m.sender_name).lower()
        if key in seen_chats:
            continue
        if cf and cf not in f"{m.sender_name} {m.sender}".lower():
            continue
        seen_chats.add(key)
        targets.append(m)
        if len(targets) >= limit:
            break

    sent, failed = [], []
    for m in targets:
        reply = await draft_reply(channel, m.sender_name or m.sender, m.body, instruction)
        if not reply:
            failed.append(m.sender_name or m.sender)
            continue
        try:
            if channel == CH_WHATSAPP:
                from .whatsapp_client import get_whatsapp
                await get_whatsapp().send(m.chat_id or m.sender, reply)
            else:
                from .instagram import get_instagram
                await asyncio.to_thread(get_instagram().send_dm, m.sender, reply)
        except Exception as e:  # noqa: BLE001
            logger.warning("reply send failed for %s on %s: %s", m.sender_name, channel, e)
            failed.append(m.sender_name or m.sender)
            continue
        store.mark_read(channel=channel, chat_id=m.chat_id)
        store.add(channel, m.sender_name or m.sender, reply, direction="out",
                  chat_id=m.chat_id or m.sender, importance="low",
                  summary="(replied) " + reply[:70])
        sent.append(m.sender_name or m.sender)

    return {"sent": sent, "failed": failed, "count": len(sent)}
